saralindqvist/miniprojekt-webbshop

package-lock.json, package.json, src/App.tsx, src/components/CheckoutPage.tsx, src/components/DetailPage.tsx, src/components/Layout.tsx, src/components/ProductPage.tsx
=> Added react router

src/components/Footer.tsx, src/components/ProductCard.tsx, src/components/ProductPage.tsx
=> fixed css for the productPage and adjusted the footer color

src/ProductData.ts
=> changed productData description to english and added SEK after the price

src/components/ProductPage.tsx
Changed paddingTop in ProductPage
closes #32
=> Changed paddingTop in ProductPage

src/components/ProductCard.tsx, src/components/ProductPage.tsx
Fixed flex-layout, title, cart button, deleted blue color on links in ProductPage
closes #35
=> Fixed flex-layout, title, cart button, deleted blue color on links

src/App.tsx, src/components/DetailPage.tsx, src/components/ProductCard.tsx, src/index.tsx
=> Errors and conflicts fixed

src/App.tsx, src/components/DetailPage.tsx, src/components/ProductCard.tsx, src/index.tsx
Reverts saralindqvist/miniprojekt-webbshop#51
=> Revert "Errors and conflicts fixed"

src/components/ProductList.tsx
made the dataGrid editable and added a quantity number
=> 54 edit adminpage

src/components/AdminProductList.tsx
Now we have a delete button which is not working yet but will try to add the functions from the context file
Co-authored-by: Fia <fiababiakandersson@users.noreply.github.com
=> added delete button, edit button and save button

src/App.tsx, src/components/AdminPage.tsx, src/components/AdminProductList.tsx, src/components/hooks/useLocalStorageState.ts, src/context/AdminContext.ts, src/context/AdminPageContext.tsx, src/context/CartContextProvider.tsx
=> Created AdminPageContext and Provider

src/App.tsx, src/components/CheckoutPage.tsx
fixed the errors of checkoutpage in the previous pr
=> inserting my code for checkoutpage in formik

src/components/CheckoutPage.tsx, src/components/EmptyCart.tsx, src/components/ShoppingCart.tsx, src/components/hooks/useLocalStorageState.ts, src/components/shared/EmptyPage.tsx, src/components/shared/HomeButton.tsx, src/context/CartContextProvider.tsx, src/index.css
see commit details (this part is not done, a few new issues are created which i will work on it later)
=> #45 promise based function when clicking confirm purchase

src/App.tsx, src/components/AdminProductList.tsx, src/components/ProductPage.tsx, src/context/AdminPageContext.tsx
Co-authored-by: Sara Lindqvist <saralindqvist@users.noreply.github>
closes #92
=> Updated productPage based on existing products in adminPage

src/components/CheckoutPage.tsx, src/components/Header.tsx, src/components/OrderConfirmation.tsx, src/components/ShoppingCart.tsx, src/context/CartContextProvider.tsx
=> #85 checkoutpage on submit

src/components/AdminProductList.tsx, src/components/CheckoutPage.tsx, src/components/OrderConfirmation.tsx, src/context/AdminPageContext.tsx
Now admin can edit product title, description and price. Saves to LS.
closes #101 
closes #95
closes #54
=> Now admin can edit price, description and title

src/components/CheckoutPage.tsx
Added responsive design for contactdetails and payment method, added error for payment method
=> #89 paymentform

src/App.tsx, src/Helper.ts, src/ShippingProviderData.ts, src/components/CheckoutPage.tsx, src/components/Header.tsx, src/components/OrderConfirmation.tsx, src/components/ShoppingCart.tsx, src/context/CartContextProvider.tsx, src/context/OrderContextProvider.tsx
as advised by Viktor :) the codes are more readable in the contexts now
=> #107 separating cart and order context

src/components/CheckoutFormContainer.tsx, src/components/Header.tsx, src/components/PaymentCreditCard.tsx, src/components/PaymentInvoice.tsx, src/components/PaymentMethod.tsx, src/components/PaymentSwish.tsx, src/context/CartContextProvider.tsx
see commit details, styling not done
=> #113 Checkout Form: input fields are only required under the chosen payment method

src/components/DeliveryOptions.tsx
=> #109 requirement for deliveryoptions 

src/App.tsx, src/components/AdminCollapsibleTable.tsx, src/components/AdminPage.tsx, src/components/AdminProductList.tsx
**Reminder:** the tsx are not named perfectly, but when you will change it dont forget to change the name of the component (function xxx ()) too as they are supposed to be the same
=> #124 separated the 2 components in AdminProductList and styling for other 2 admin components (but not AdminProductList)

src/components/AddProductForm.tsx, src/components/PaymentCreditCard.tsx
=> #126 Made it only possible to write numbers in "price" when adding new products

src/components/AddProductForm.tsx, src/components/NewProductConfirmation.tsx
=> Made new product confirmation pop up

src/components/AddProductForm.tsx, src/components/Modal.tsx
Put styling in modal and made modal responsive. Now theres no scroll when modal is open, but still a bug : scroll doesnt come back immediately after modal is closed.
closes #131
=> #131 Modal styling

src/components/ProductCard.tsx, src/components/ProductPage.tsx, src/context/AdminPageContext.tsx, src/context/CartContextProvider.tsx, src/context/OrderContextProvider.tsx
done for product list and product page, not for admin product list since teammates are still working on it
=> #136 replace props with admin context 

src/components/AdminCollapsibleTable.tsx, src/components/AdminPage.tsx, src/components/AdminProductList.tsx, src/components/RemoveProductConfirmation.tsx, src/context/AdminPageContext.tsx
Now there is a conformation pop up when you press delete.
To make sure if you really want to delete the item or not!
=> now there is a pop up to confirm if you want to remove a product

src/App.tsx, src/components/AddProductForm.tsx, src/components/DeliveryDetails.tsx, src/components/PaymentCreditCard.tsx, src/components/PaymentInvoice.tsx, src/components/PaymentSwish.tsx
=> #134 payment method styling for requirement

src/App.tsx, src/ProductData.ts, src/components/DetailPage.tsx, src/components/Footer.tsx, src/components/Header.tsx, src/components/StartPage.tsx, src/components/cart-checkout/CheckoutFormContainer.tsx, src/components/cart-checkout/CheckoutPage.tsx, src/components/cart-checkout/CustomerDetails.tsx, src/components/cart-checkout/DeliveryOptions.tsx, src/components/cart-checkout/OrderConfirmation.tsx, src/components/cart-checkout/PaymentMethod.tsx, src/components/cart-checkout/PriceOverview.tsx, src/components/cart-checkout/ShoppingCart.tsx, src/components/cart-checkout/payment-methods/PaymentCreditCard.tsx, src/components/cart-checkout/payment-methods/PaymentInvoice.tsx, src/components/cart-checkout/payment-methods/PaymentSwish.tsx, src/components/shared/HomeButton.tsx, src/context/CartContextProvider.tsx, src/context/OrderContextProvider.tsx
adjusted styling on responsive design as well
=> #137-1 added comments, organised the cart/order components and moved them under folders

src/App.tsx, src/ProductData.ts, src/components/Footer.tsx, src/components/Header.tsx, src/components/StartPage.tsx
Got in 6 random pictures at the end to satisfy the responsive design 🥇
=> #145 Homepage

src/components/cart-checkout/CheckoutFormContainer.tsx, src/components/cart-checkout/payment-methods/PaymentCreditCard.tsx
=> Fixed responsive design for mobile (payment method)

src/components/Admin/AdminCollapsibleTable.tsx, src/components/Admin/AdminProductList.tsx, src/components/Admin/Modal.tsx
=> Fixed modal background

src/components/cart-checkout/CheckoutFormContainer.tsx, src/components/cart-checkout/payment-methods/PaymentSwish.tsx
-now the phone number entered by the user will automatically appear if swish is chosen 
closes #160
=> fixed import of phone number
